# Generated by Django 5.2.6 on 2025-11-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Computador, Telemóvel, TV', max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('defeito_relatado', models.TextField(help_text='Descrição do defeito pelo cliente.')),
                ('status_atual', models.CharField(choices=[('aberto', 'Aberta'), ('em_analise', 'Em Análise'), ('aguardando_peca', 'Aguardando Peça'), ('em_reparo', 'Em Reparo'), ('concluido', 'Concluído'), ('entregue', 'Entregue ao Cliente')], default='aberto', max_length=20)),
                ('codigo_consulta', models.CharField(default='FF1FAFC6', editable=False, max_length=8, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.equipamento')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('novo_status', models.CharField(choices=[('aberto', 'Aberta'), ('em_analise', 'Em Análise'), ('aguardando_peca', 'Aguardando Peça'), ('em_reparo', 'Em Reparo'), ('concluido', 'Concluído'), ('entregue', 'Entregue ao Cliente')], max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text="Detalhes da atualização (ex: 'Diagnóstico: Placa-mãe danificada')")),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.ordemdeservico')),
            ],
            options={
                'verbose_name': 'Atualização de Status',
                'verbose_name_plural': 'Atualizações de Status',
                'ordering': ['data_atualizacao'],
            },
        ),
    ]
